name = "Influencer Analytics"
client_id = "85712f0b474c2d3939642ad3b1085885"
application_url = "https://api.influtrak.com"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,read_discounts,write_discounts,write_script_tags,read_script_tags,read_pixels,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://api.influtrak.com/api/auth/callback",
  "https://api.influtrak.com/api/shopify/callback"
]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://api.influtrak.com"
subpath = "influencer"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "clikn01.myshopify.com"
