name = "Influencer Analytics"
client_id = "85712f0b474c2d3939642ad3b1085885"
application_url = "https://influ-connect.replit.app"
embedded = true

[access_scopes]
scopes = "write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://influ-connect.replit.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://influ-connect.replit.app/api/webhooks/app/uninstalled"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "clikn01.myshopify.com"
